-- Create Students Table
create table public.students (
  id bigint generated by default as identity primary key,
  roll text not null unique,
  name text not null,
  phone text not null
);

-- Create Attendance Table
create table public.attendance (
  id bigint generated by default as identity primary key,
  student_roll text not null references public.students (roll),
  status text not null, -- 'PRESENT' or 'ABSENT',
  reason text,
  transcript text,
  date date not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert Dummy Data for Testing
insert into public.students (roll, name, phone)
values 
  ('21A01', 'Alice Johnson', '+919876543210'), -- Replace with your real phone number to test calls!
  ('21A02', 'Bob Smith', '+919988776655');
